"""
Generate coastline-clipped tile shapes for coastal cells only.

Interior cells stay as rectangles (generated by the UI).
Coastal cells get irregular polygons clipped to the Natural Earth coastline.
Multi-polygon support: cells split by water produce multiple polygon entries.

Output: data/tiles/tile_shapes.bin
  Binary format: uint32 cell_count, then per entry:
    uint32 grid_index, uint16 n_vertices, float32 lon, float32 lat, ...
  Same grid_index may appear multiple times (multi-polygon cells).
"""

import numpy as np
import json
import struct
import time
from pathlib import Path
from shapely.geometry import box, shape, MultiPolygon, Polygon
from shapely.ops import unary_union
from shapely import STRtree

TILES_DIR = Path("data/tiles")
NATURAL_EARTH_DIR = Path("data/natural_earth")

GRID_WIDTH = 1440
GRID_HEIGHT = 601
RESOLUTION = 0.25
HALF = RESOLUTION / 2


def load_land_polygons():
    import zipfile, io, requests, shapefile

    land_dir = NATURAL_EARTH_DIR / "land"
    shp_files = list(land_dir.glob("*.shp")) if land_dir.exists() else []
    if not shp_files:
        print("  Downloading Natural Earth 10m land...")
        url = "https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_land.zip"
        resp = requests.get(url, timeout=120)
        land_dir.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(io.BytesIO(resp.content)) as zf:
            zf.extractall(land_dir)
        shp_files = list(land_dir.glob("*.shp"))

    print(f"  Loading {shp_files[0].name}...")
    sf = shapefile.Reader(str(shp_files[0]))
    polys = []
    for s in sf.shapes():
        try:
            g = shape(s.__geo_interface__)
            polys.append(g if g.is_valid else g.buffer(0))
        except Exception:
            pass

    islands_dir = NATURAL_EARTH_DIR / "minor_islands"
    island_shps = list(islands_dir.glob("*.shp")) if islands_dir.exists() else []
    if island_shps:
        print(f"  Loading {island_shps[0].name}...")
        sf2 = shapefile.Reader(str(island_shps[0]))
        for s in sf2.shapes():
            try:
                g = shape(s.__geo_interface__)
                polys.append(g if g.is_valid else g.buffer(0))
            except Exception:
                pass

    print(f"  Merging {len(polys)} polygons...")
    merged = unary_union(polys)
    print(f"  Land geometry ready.")
    return merged


def load_land_mask():
    cache = NATURAL_EARTH_DIR / "land_mask_025.npy"
    if cache.exists():
        return np.load(cache)
    raise FileNotFoundError(f"Land mask not found at {cache}")


def clip_cell(cell_box, land_geom, tree):
    """Clip a cell rectangle against land. Returns list of polygons, or None."""
    hits = tree.query(cell_box, predicate="intersects")
    if len(hits) == 0:
        return None

    clipped = cell_box.intersection(land_geom)
    if clipped.is_empty:
        return None

    if isinstance(clipped, MultiPolygon):
        parts = list(clipped.geoms)
    elif isinstance(clipped, Polygon):
        parts = [clipped]
    else:
        return None

    result = []
    for poly in parts:
        if poly.is_empty or poly.area < 1e-6:
            continue
        result.append(list(poly.exterior.coords))

    return result if result else None


def main():
    t0 = time.time()
    print("=" * 60)
    print("  Coastline-Clipped Tile Shapes (coastal cells only)")
    print("=" * 60)

    land_mask = load_land_mask()
    land_index = np.where(land_mask.ravel())[0]
    n_land = len(land_index)
    print(f"  Land cells: {n_land:,}")

    land_geom = load_land_polygons()

    if isinstance(land_geom, MultiPolygon):
        parts = list(land_geom.geoms)
    else:
        parts = [land_geom]
    tree = STRtree(parts)
    print(f"  Spatial index: {len(parts)} parts")

    print("\n  Classifying cells...")
    t1 = time.time()

    cell_shapes = []
    n_rect = 0
    n_clipped = 0
    total_vertices = 0
    max_fragments = 0

    for i, gi in enumerate(land_index):
        if i % 50000 == 0:
            elapsed = time.time() - t1
            print(f"    {i:,}/{n_land:,} ({elapsed:.1f}s)")

        lat_idx = gi // GRID_WIDTH
        lon_idx = gi % GRID_WIDTH
        lon = lon_idx * RESOLUTION
        if lon > 180:
            lon -= 360
        lat = 90.0 - lat_idx * RESOLUTION

        cell = box(lon - HALF, lat - HALF, lon + HALF, lat + HALF)

        if land_geom.contains(cell):
            n_rect += 1
            continue

        clipped = clip_cell(cell, land_geom, tree)
        if clipped is None:
            n_rect += 1
            continue

        n_frags = 0
        for poly_coords in clipped:
            if len(poly_coords) < 4:
                continue
            n_clipped += 1
            n_frags += 1
            total_vertices += len(poly_coords)
            cell_shapes.append((int(gi), poly_coords))
        max_fragments = max(max_fragments, n_frags)

    elapsed = time.time() - t1
    print(f"\n  Classification done in {elapsed:.0f}s")
    print(f"  Interior (rectangle): {n_rect:,}")
    print(f"  Coastal entries:      {n_clipped:,}")
    print(f"  Max fragments/cell:   {max_fragments}")
    print(f"  Total vertices:       {total_vertices:,}")
    print(f"  Avg vertices/entry:   {total_vertices / max(len(cell_shapes),1):.1f}")

    print("\n  Writing binary file...")
    bin_path = TILES_DIR / "tile_shapes.bin"
    with open(bin_path, "wb") as f:
        f.write(struct.pack("<I", len(cell_shapes)))
        for gi, coords in cell_shapes:
            f.write(struct.pack("<I", gi))
            f.write(struct.pack("<H", len(coords)))
            for lon, lat in coords:
                f.write(struct.pack("<ff", lon, lat))

    bin_size = bin_path.stat().st_size
    print(f"  tile_shapes.bin: {bin_size / 1e6:.1f} MB")

    total_elapsed = time.time() - t0
    print(f"\n{'=' * 60}")
    print(f"  Done in {total_elapsed:.0f}s")
    print(f"  Binary file: {bin_size / 1e6:.1f} MB")
    print(f"  Entries: {len(cell_shapes):,} ({n_rect:,} rect skipped + {n_clipped:,} clipped)")
    print(f"  Max fragments per cell: {max_fragments}")
    print("=" * 60)


if __name__ == "__main__":
    main()
